# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}    
    - run: npm ci
    - run: npm run build --if-present   
    - run: npm test --coverage=true
    - name: Run unit test
      uses: mattallty/jest-github-action@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # this is just an example, this could be any command that will trigger jest
        test-command: "npm test --coverage"
        #coverage-comment: true
    #- run: npm test 
       
    - name: Run linters & prettier
      uses: wearerequired/lint-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Enable linters
        eslint: true
        prettier: true
    - name: Download Polaris_CLI
      shell: bash
      run: wget 'https://ikea.polaris.synopsys.com/api/tools/polaris_cli-linux64.zip'
    - name: Unzip Polaris_CLI zip file
      shell: bash
      run: unzip polaris_cli-linux64.zip   
    - name: Set access as executable on Polaris_CLI and export to path
      shell : bash
      run: |  
            POLARIS_BIN=$(unzip -Z -1 polaris_cli-linux64.zip | head -1)
            chmod +x $(pwd)/${POLARIS_BIN}polaris
            echo "$(pwd)/${POLARIS_BIN}" >> $GITHUB_PATH    
    - name: Set Polaris_CLI env variables in file polaris.yaml
      shell: bash
      run: |
        cat <<EOT >> polaris.yaml
          version: "1"
          project: 
            name:  $(echo $GITHUB_REPOSITORY | awk -F /'{print $2}')
            branch: $GITHUB_REF
            revision:
              name: '$(git rev-parse --short "$GITHUB_SHA")'
              date: '$(date +'%FT%TZ')'
              modified: true
          capture:
            fileSystem: 
              javascript:
                extensions: [js]
                files:
                - directory: ./
                - excludeRegex: node_modules|bower_components|vendor
          analyze:
            mode: central      
          install: # Version settings for tools to use
            coverity:
              version: default
        EOT
    - name: Run Polaris Scan
      shell : bash 
      env: 
        POLARIS_ACCESS_TOKEN: ${{inputs.POLARIS_ACCESS_TOKEN}}
        POLARIS_SERVER_URL: ${{inputs.POLARIS_SERVER_URL}}
      run: |     
          polaris -c polaris.yaml capture
          polaris -c polaris.yaml analyze -w
    #- name: Static Analysis with Polaris Action
     # uses: devsecops-test/polaris-action@v1
     # with:
     #   polarisServerUrl: ${{secrets.POLARIS_SERVER_URL_CSPROD}}
     #   polarisAccessToken: ${{secrets.POLARIS_ACCESS_TOKEN_CSPROD}}
      #  polarisProjectName: polaris-action-sample
       # polarisCli: https://ikea.polaris.synopsys.com/api/tools/polaris_cli-linux64.zip
   # -- Build your project here -- eg. mvn clean package
    #- name: Polaris
     # uses: blackducksoftware/github-action@2.0.1
     # with:
       # args: --polaris.url="${{ secrets.POLARIS_URL}}" --polaris.access.token="${{ secrets.POLARIS_TOKEN}}" --detect.tools="POLARIS"
    #- name: Synopsys Detect
    #  uses: blackducksoftware/github-action@2.0.0
    #  with:
    #    args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.risk.report.pdf=true'

